### ISSUE TITLE
Accessing api.keptn.DOMAIN/v1/events without query params results in an error

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1210]
When accessing `api.keptn.DOMAIN/v1/events` without any parameters the Api Server prints the following error:

```
2019/12/08 09:37:13 Serving  at http://[::]:8080
{"timestamp":"2019-12-08T12:42:24.931740505Z","logLevel":"INFO","message":"API received a keptn event"}
{"timestamp":"2019-12-08T12:47:20.08956808Z","logLevel":"INFO","message":"API received a keptn event"}
{"timestamp":"2019-12-08T12:54:58.893848056Z","logLevel":"INFO","message":"API received a keptn event"}
2019/12/09 11:05:51 http: panic serving 10.8.0.33:55984: runtime error: invalid memory address or nil pointer dereference
goroutine 136 [running]:
net/http.(*conn).serve.func1(0xc000380280)
    /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x15db520, 0x2792df0)
    /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/keptn/keptn/api/handlers.GetEventHandlerFunc(0xc00016eb00, 0x0, 0x0, 0xc000752080, 0xc0007b4901, 0xc00030a040)
    /go/src/github.com/keptn/keptn/api/handlers/event.go:71 +0x3b
github.com/keptn/keptn/api/restapi/operations/event.GetEventHandlerFunc.Handle(0x1864f08, 0xc00016eb00, 0x0, 0x0, 0xc000752080, 0x0, 0x0)
    /go/src/github.com/keptn/keptn/api/restapi/operations/event/get_event.go:21 +0x4e
github.com/keptn/keptn/api/restapi/operations/event.(*GetEvent).ServeHTTP(0xc000379ce0, 0x1a3a000, 0xc000718620, 0xc00016eb00)
    /go/src/github.com/keptn/keptn/api/restapi/operations/event/get_event.go:69 +0x287
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1a3a000, 0xc000718620, 0xc00016ea00)
    /go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0002e8230, 0x1a3a000, 0xc000718620, 0xc00016ea00)
    /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1a3a000, 0xc000718620, 0xc00016e100)
    /go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc0007885c0, 0x1a3a000, 0xc000718620, 0xc00016e100)
    /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x1a3a000, 0xc000718620, 0xc00016e100)
    /go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x2a5
net/http.HandlerFunc.ServeHTTP(0xc00051d140, 0x1a3a000, 0xc000718620, 0xc00016e100)
    /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x1a3a000, 0xc000718620, 0xc00016e100)
    /go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc00051d180, 0x1a3a000, 0xc000718620, 0xc00016e100)
    /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/keptn/keptn/api/restapi.setupGlobalMiddleware.func1(0x1a3a000, 0xc000718620, 0xc00016e100)
    /go/src/github.com/keptn/keptn/api/restapi/configure.go:148 +0xe0
net/http.HandlerFunc.ServeHTTP(0xc000788a20, 0x1a3a000, 0xc000718620, 0xc00016e100)
    /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc0006c9790, 0x1a3a000, 0xc000718620, 0xc00016e100)
    /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000380280, 0x1a3ef00, 0xc00004be00)
    /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

Apparently it is required to set the following two parameters to make it work:

* `keptnContext`
* `type`

The API should either print a proper validation error message and return status code 400, or it should accept the empty parameters (to be honest, not providing a `type` should work).

**Comment by christian-kreuzberger-dtx** [comment]
Fix together with #1234
