### ISSUE TITLE
Mongodb-datastore runs in an error: `context deadline exceeded` when two users access the Bridge

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1440]
**End-user problem:** Keptn's Bridge does not show events of a service even though there are events available. 
![image](https://user-images.githubusercontent.com/729071/75774462-5bf87d80-5d50-11ea-8ef7-2f5375933356.png)

The issue might not be related to the _Keptn's Bridge_ in the first place, because the `mongodb-datastore` is running in an error (see below). 

**Environment**
* Keptn Version (`keptn version`): 0.6.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): Rancher
* Kubernetes version (`kubectl version`): v1.16.6

* Version of `mongodb-datastore`: 
```
##########
branch: bridge2
repository: https://github.com/keptn/keptn
commitlink: https://github.com/keptn/keptn/commit/1107baa82983d0b272aa88e15e9acb8ad897988d
repolink: https://github.com/keptn/keptn/tree/1107baa82983d0b272aa88e15e9acb8ad897988d
travisbuild: https://travis-ci.org/keptn/keptn/jobs/644257849
timestamp: 20200131.1010
##########
```

* Versin of `bridge`:
```
##########
branch: feature/1323/evaluation-results-comparison
repository: https://github.com/keptn/keptn
commitlink: https://github.com/keptn/keptn/commit/5a5d92209d8823d2c0db5e8745f475aa42d7b5cb
repolink: https://github.com/keptn/keptn/tree/5a5d92209d8823d2c0db5e8745f475aa42d7b5cb
travisbuild: https://travis-ci.org/keptn/keptn/jobs/652758669
timestamp: 20200220.0107
##########
```

The error occurs in the `mongodb-datastore`, with the following error message: 

```
{"timestamp":"2020-03-02T13:39:47.918860979Z","logLevel":"DEBUG","message":"getting events from the data store"}
{"timestamp":"2020-03-02T13:39:47.920172961Z","logLevel":"DEBUG","message":"filter FromTime"}
{"timestamp":"2020-03-02T13:39:50.570360445Z","logLevel":"DEBUG","message":"getting events from the data store"}
{"timestamp":"2020-03-02T13:39:50.572143416Z","logLevel":"DEBUG","message":"filter FromTime"}
{"timestamp":"2020-03-02T13:39:50.882809981Z","logLevel":"ERROR","message":"error counting elements in events collection: context deadline exceeded"}
{"timestamp":"2020-03-02T13:39:50.89363922Z","logLevel":"ERROR","message":"error finding elements in events collection: context deadline exceeded"}
{"timestamp":"2020-03-02T13:39:50.898304849Z","logLevel":"ERROR","message":"error counting elements in events collection: context deadline exceeded"}
{"timestamp":"2020-03-02T13:39:50.899039807Z","logLevel":"ERROR","message":"error finding elements in events collection: context deadline exceeded"}
2020/03/02 13:39:50 http: panic serving 10.42.1.43:35816: runtime error: invalid memory address or nil pointer dereference
goroutine 22092202 [running]:
net/http.(*conn).serve.func1(0xc00766af00)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x16cd240, 0x29c56f0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
go.mongodb.org/mongo-driver/mongo.(*Cursor).Next(0x0, 0x1bf8620, 0xc002db4f00, 0x1)
        /go/pkg/mod/go.mongodb.org/mongo-driver@v1.1.1/mongo/cursor.go:93 +0x43
github.com/keptn/keptn/mongodb-datastore/handlers.GetEvents(0xc000180800, 0xc0087d1d30, 0xc0087d1d40, 0x0, 0xc000b34fc8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/keptn/keptn/mongodb-datastore/handlers/events.go:198 +0x919
github.com/keptn/keptn/mongodb-datastore/restapi.configureAPI.func2(0xc000180800, 0xc0087d1d30, 0xc0087d1d40, 0x0, 0xc000b34fc8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/keptn/keptn/mongodb-datastore/restapi/configure_mongodb_datastore.go:51 +0x60
github.com/keptn/keptn/mongodb-datastore/restapi/operations/event.GetEventsHandlerFunc.Handle(0x1967510, 0xc000180800, 0xc0087d1d30, 0xc0087d1d40, 0x0, 0xc000b34fc8, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/keptn/keptn/mongodb-datastore/restapi/operations/event/get_events.go:25 +0x53
github.com/keptn/keptn/mongodb-datastore/restapi/operations/event.(*GetEvents).ServeHTTP(0xc000366b00, 0x1bf3560, 0xc004730540, 0xc000180800)
        /go/src/github.com/keptn/keptn/mongodb-datastore/restapi/operations/event/get_events.go:60 +0x238
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1bf3560, 0xc004730540, 0xc000180800)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc00042faa0, 0x1bf3560, 0xc004730540, 0xc000180800)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1bf3560, 0xc004730540, 0xc000180600)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc0007e76c0, 0x1bf3560, 0xc004730540, 0xc000180600)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x1bf3560, 0xc004730540, 0xc000180600)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x2a5
net/http.HandlerFunc.ServeHTTP(0xc0007f6440, 0x1bf3560, 0xc004730540, 0xc000180600)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x1bf3560, 0xc004730540, 0xc000180600)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc0007f6480, 0x1bf3560, 0xc004730540, 0xc000180600)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/keptn/keptn/mongodb-datastore/restapi.setupGlobalMiddleware.func1(0x1bf3560, 0xc004730540, 0xc000180600)
        /go/src/github.com/keptn/keptn/mongodb-datastore/restapi/configure_mongodb_datastore.go:116 +0x252
net/http.HandlerFunc.ServeHTTP(0xc0007e7b20, 0x1bf3560, 0xc004730540, 0xc000180600)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc000490270, 0x1bf3560, 0xc004730540, 0xc000180600)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00766af00, 0x1bf85a0, 0xc004ce5600)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
{"timestamp":"2020-03-02T13:39:50.922836774Z","logLevel":"ERROR","message":"error counting elements in events collection: context deadline exceeded"}
{"timestamp":"2020-03-02T13:39:50.923944496Z","logLevel":"ERROR","message":"error finding elements in events collection: context deadline exceeded"}
```

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Gatekeeper
* [x] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
* A Keptn-user has the bridge open in a browser tab (all the time) and permanently fetching for new events. 
* Another Keptn-user wants to access the bridge and runs into the problem explained above. 

**Additional context**
* Is the MongoDB locked by requests from the Keptn's bridge of the first user?

**Comment by christian-kreuzberger-dtx** [comment]
We are currently investigating this issue. It seems that there might be a memory leak in mongodb-datastore causing this issue.

**Comment by tashrifbillah** [comment]
For me, `-j 1` did the job.

> mongorestore --help

> -j, --numParallelCollections=                             number of collections to restore in parallel
