### ISSUE TITLE
Project with two stages broken after lighthouse run at second stage 

### ISSUE THREAD

**Issue by heydenb** [keptn/keptn#1695]
**Environment**
Running on AKS. Integration with Azure DevOps pipeline - Quality Gates only

* Client OS (e.g., Linux, OSX, Windows): from pipeline
* Keptn Version (`keptn version`): 0.6.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): AKS
* Kubernetes version (`kubectl version`): v1.15.10

**Affected Component**
configuration-service
lighthouse
helm?

**Describe the bug**
I have setup a project (kbi) with two stages for quality gates only. See my shipyard.yaml.
I have included sli's for each stage and an slo.
All works well when I only send an event for one stage. (ac2)
From the moment I send the event for the second stage (acc), the bridge is broken and does not show the project anymore.
I could fix it by browsing the configuration-service. /data/config/kbi/inburgering/acc contains a helm dir with a dynatrace-generated.tgz file. When I stashed this structure it works again.
This is repeatable. Next run, same result.

**To Reproduce**
shipyard.yaml:
~~~~
stages:
  - name: "ac2"
  - name: "acc"
~~~~
steps
~~~~
keptn create project kbi --shipyard=./shipyard.yaml
keptn create service inburgering --project=kbi
git clone --branch release-0.3.0 https://github.com/keptn-contrib/dynatrace-sli-service --single-branch
kubectl apply -f dynatrace-sli-service/deploy/service.yaml
keptn add-resource --project=kbi --stage=ac2 --service=inburgering --resource=./dynatrace-slis.yaml --resourceUri=dynatrace/sli.yaml
keptn add-resource --project=kbi --stage=acc --service=inburgering --resource=./dynatrace-slis.yaml --resourceUri=dynatrace/sli.yaml
kubectl create secret generic dynatrace-credentials-kbi -n "keptn" --from-file=dynatrace-credentials=dynatrace-creds.yaml
kubectl apply -f lighthouse_source_dynatrace.yaml
keptn add-resource --project=kbi --service=inburgering --stage=ac2 --resource=slo.yaml --resourceUri=slo.yaml
keptn add-resource --project=kbi --service=inburgering --stage=acc --resource=slo.yaml --resourceUri=slo.yaml
~~~~

Then send the event
`keptn send event -f ./start-evaluation-event.json`
~~~~
{
  "type": "sh.keptn.event.start-evaluation",
  "specversion": "0.2",
  "contenttype": "application/json",
  "source": "test-event",
  "data": {
      "start": "2020-04-22T17:07:59+02:00",
      "end": "2020-04-22T17:12:18+02:00", 
      "project": "kbi",
      "service": "inburgering", 
      "stage": "ac2", 
      "teststrategy": "performance" 
  }
}
~~~~

Result as expected.

Then send the event again but with stage acc.
~~~~
{
  "type": "sh.keptn.event.start-evaluation",
  "specversion": "0.2",
  "contenttype": "application/json",
  "source": "test-event",
  "data": {
      "start": "2020-04-22T17:07:59+02:00",
      "end": "2020-04-22T17:12:18+02:00", 
      "project": "kbi",
      "service": "inburgering", 
      "stage": "acc", 
      "teststrategy": "performance" 
  }
}
~~~~

**Expected behavior**
Should work

**Current behavior**
Keptn bridge is broken.

**Screenshots**
Keptn bridge is broken.
![image](https://user-images.githubusercontent.com/2580178/80112698-ae506080-8581-11ea-8143-943cb19537ca.png)
See how configuration-service looks like
![image](https://user-images.githubusercontent.com/2580178/80113003-07b88f80-8582-11ea-9520-a601390d9c8d.png)

Removing the helm dir fixes the issue.

**Comment by christian-kreuzberger-dtx** [comment]
I'm suspecting that there is an issue with helm-service.

Can you please provide the following outputs:

1.
```console
kubectl -n keptn get pods
```
2.
```console
kubectl -n keptn logs svc/helm-service
```
3.
```console
kubectl -n keptn logs svc/gatekeeper-service
```

**Comment by heydenb** [comment]
1.
~~~~
NAME                                                              READY   STATUS    RESTARTS   AGE
api-f5c7c88b5-x6cfq                                               1/1     Running   0          2d19h
bridge-7b8c997f6f-r7qd9                                           1/1     Running   0          2d19h
configuration-service-54c4f54449-mj68r                            1/1     Running   0          2d19h
dynatrace-sli-service-87549f6ff-n292m                             1/1     Running   0          2d19h
dynatrace-sli-service-monitoring-configure-distributor-855d69mb   1/1     Running   0          2d19h
eventbroker-go-64cc9796-bpptj                                     1/1     Running   0          2d19h
gatekeeper-service-644bcf47b4-cq85s                               1/1     Running   0          2d19h
gatekeeper-service-evaluation-done-distributor-589cff558d-ljr4l   1/1     Running   0          2d19h
helm-service-configuration-change-distributor-5c6f5b47f-jkg97     1/1     Running   0          2d19h
helm-service-d5dfbcbbd-s6gf9                                      1/1     Running   0          2d19h
helm-service-service-create-distributor-74595dfdd9-xzqch          1/1     Running   0          2d19h
jmeter-service-7d8f898c98-5jc48                                   1/1     Running   0          2d19h
jmeter-service-deployment-distributor-84956cc6c9-dgwfz            1/1     Running   0          2d19h
keptn-nats-cluster-1                                              1/1     Running   0          2d19h
lighthouse-service-765db94d75-g94tl                               1/1     Running   0          2d19h
lighthouse-service-distributor-68d885856c-hs6xs                   1/1     Running   0          2d19h
nats-operator-85db6c4c9b-d9dc6                                    1/1     Running   0          2d19h
remediation-service-f5cb5658f-qhlkt                               1/1     Running   0          2d19h
remediation-service-problem-distributor-69759845bf-mpjw2          1/1     Running   0          2d19h
shipyard-service-845f874dc5-gv7c7                                 1/1     Running   0          2d19h
shipyard-service-create-project-distributor-5fb5c7dd49-mf7m2      1/1     Running   0          2d19h
shipyard-service-delete-project-distributor-57885cbdd6-j4ckc      1/1     Running   0          2d19h
wait-service-7666866767-2qkr9                                     1/1     Running   0          2d19h
wait-service-deployment-distributor-5d479c44d9-wbk4q              1/1     Running   0          2d19h
~~~~
2.
~~~~
{"timestamp":"2020-04-23T13:11:40.50136394Z","logLevel":"DEBUG","message":"No WebSocket connection data available"}
{"timestamp":"2020-04-23T13:11:40.569106277Z","logLevel":"ERROR","message":"Error when reading chart inburgering-generated from project kbi: Get http://configuration-service.keptn.svc.cluster.local:8080/v1/project/kbi/stage/ac2/service/inburgering/resource/helm%2Finburgering-generated.tgz: EOF"}
{"timestamp":"2020-04-23T13:20:51.427303768Z","logLevel":"DEBUG","message":"No WebSocket connection data available"}
{"timestamp":"2020-04-23T13:20:51.46376257Z","logLevel":"ERROR","message":"Error when reading chart inburgering-generated from project kbi: Get http://configuration-service.keptn.svc.cluster.local:8080/v1/project/kbi/stage/acc/service/inburgering/resource/helm%2Finburgering-generated.tgz: EOF"}
~~~~
3.
~~~~
{"timestamp":"2020-04-23T13:11:40.515905512Z","logLevel":"INFO","message":"Promote service inburgering of project kbi to stage acc"}
{"timestamp":"2020-04-23T13:11:40.691792436Z","logLevel":"ERROR","message":"Error when reading chart inburgering from project kbi: Get http://configuration-service.keptn.svc.cluster.local:8080/v1/project/kbi/stage/ac2/service/inburgering/resource/helm%2Finburgering.tgz: EOF"}
{"timestamp":"2020-04-23T13:20:51.39135342Z","logLevel":"INFO","message":"Service inburgering of project kbi in stage acc has passed the evaluation"}
{"timestamp":"2020-04-23T13:20:51.445039577Z","logLevel":"INFO","message":"No further stage available to promote the service inburgering of project kbi"}
~~~~
Looks to me it has to do with the missing/uncommitted resources in the configuration-service. Let me add that log as well.
Bingo ...
~~~~
{"timestamp":"2020-04-23T13:11:39.654243715Z","logLevel":"DEBUG","message":"Checking out ac2 branch"}
{"timestamp":"2020-04-23T13:11:39.767137174Z","logLevel":"DEBUG","message":"Checking out master branch"}
{"timestamp":"2020-04-23T13:11:39.7843765Z","logLevel":"DEBUG","message":"Checking out ac2 branch"}
{"timestamp":"2020-04-23T13:11:39.799890144Z","logLevel":"DEBUG","message":"Checking out ac2 branch"}
{"timestamp":"2020-04-23T13:11:40.272087175Z","logLevel":"DEBUG","message":"Checking out ac2 branch"}
{"timestamp":"2020-04-23T13:11:40.507844594Z","logLevel":"DEBUG","message":"Checking out master branch"}
{"timestamp":"2020-04-23T13:11:40.528727883Z","logLevel":"DEBUG","message":"Checking out ac2 branch"}
{"timestamp":"2020-04-23T13:11:40.551279455Z","logLevel":"DEBUG","message":"Archive the Helm chart: helm/inburgering.tgz"}
2020/04/23 13:11:40 http: panic serving 10.244.2.37:47460: runtime error: invalid memory address or nil pointer dereference
goroutine 1570 [running]:
net/http.(*conn).serve.func1(0xc0000defa0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x16f7bc0, 0x29a51e0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/keptn/keptn/configuration-service/handlers.GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHandlerFunc(0xc000465300, 0xc00021949b, 0xc000648f70, 0x3, 0xc0000b9f80, 0x14, 0xc000648f86, 0xb, 0xc000648f7a, 0x3, ...)
	/go/src/github.com/keptn/keptn/configuration-service/handlers/service_resource.go:54 +0xc36
github.com/keptn/keptn/configuration-service/restapi/operations/service_resource.GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHandlerFunc.Handle(0x19c3638, 0xc000465300, 0xc00021949b, 0xc000648f70, 0x3, 0xc0000b9f80, 0x14, 0xc000648f86, 0xb, 0xc000648f7a, ...)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/operations/service_resource/get_project_project_name_stage_stage_name_service_service_name_resource_resource_uri.go:19 +0x42
github.com/keptn/keptn/configuration-service/restapi/operations/service_resource.(*GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURI).ServeHTTP(0xc0005e3ec0, 0x1bb9aa0, 0xc000798700, 0xc000465300)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/operations/service_resource/get_project_project_name_stage_stage_name_service_service_name_resource_resource_uri.go:54 +0x212
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1bb9aa0, 0xc000798700, 0xc000465300)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0006b4ac0, 0x1bb9aa0, 0xc000798700, 0xc000465300)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1bb9aa0, 0xc000798700, 0xc000465100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc000947dc0, 0x1bb9aa0, 0xc000798700, 0xc000465100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x1bb9aa0, 0xc000798700, 0xc000465100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x2a5
net/http.HandlerFunc.ServeHTTP(0xc00094a180, 0x1bb9aa0, 0xc000798700, 0xc000465100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x1bb9aa0, 0xc000798700, 0xc000465100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc00094a1c0, 0x1bb9aa0, 0xc000798700, 0xc000465100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/keptn/keptn/configuration-service/restapi.setupGlobalMiddleware.func1(0x1bb9aa0, 0xc000798700, 0xc000465100)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/configure_configuration_service.go:179 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc00094e220, 0x1bb9aa0, 0xc000798700, 0xc000465100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc000828680, 0x1bb9aa0, 0xc000798700, 0xc000465100)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0000defa0, 0x1bbeaa0, 0xc00094ae40)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
{"timestamp":"2020-04-23T13:11:40.560386763Z","logLevel":"DEBUG","message":"Checking out ac2 branch"}
2020/04/23 13:11:40 http: panic serving 10.244.0.27:43442: runtime error: invalid memory address or nil pointer dereference
goroutine 1565 [running]:
net/http.(*conn).serve.func1(0xc000504820)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x16f7bc0, 0x29a51e0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/keptn/keptn/configuration-service/handlers.GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHandlerFunc(0xc000523f00, 0xc000304548, 0xc00063c9b0, 0x3, 0xc0005008c0, 0x1e, 0xc00063c9c6, 0xb, 0xc00063c9ba, 0x3, ...)
	/go/src/github.com/keptn/keptn/configuration-service/handlers/service_resource.go:54 +0xc36
github.com/keptn/keptn/configuration-service/restapi/operations/service_resource.GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHandlerFunc.Handle(0x19c3638, 0xc000523f00, 0xc000304548, 0xc00063c9b0, 0x3, 0xc0005008c0, 0x1e, 0xc00063c9c6, 0xb, 0xc00063c9ba, ...)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/operations/service_resource/get_project_project_name_stage_stage_name_service_service_name_resource_resource_uri.go:19 +0x42
github.com/keptn/keptn/configuration-service/restapi/operations/service_resource.(*GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURI).ServeHTTP(0xc0005e3ec0, 0x1bb9aa0, 0xc0004cc540, 0xc000523f00)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/operations/service_resource/get_project_project_name_stage_stage_name_service_service_name_resource_resource_uri.go:54 +0x212
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1bb9aa0, 0xc0004cc540, 0xc000523f00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0006b4ac0, 0x1bb9aa0, 0xc0004cc540, 0xc000523f00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc000947dc0, 0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x2a5
net/http.HandlerFunc.ServeHTTP(0xc00094a180, 0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc00094a1c0, 0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/keptn/keptn/configuration-service/restapi.setupGlobalMiddleware.func1(0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/configure_configuration_service.go:179 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc00094e220, 0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc000828680, 0x1bb9aa0, 0xc0004cc540, 0xc000465700)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000504820, 0x1bbeaa0, 0xc00075c380)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
{"timestamp":"2020-04-23T13:11:40.568667179Z","logLevel":"DEBUG","message":"Archive the Helm chart: helm/inburgering-generated.tgz"}
{"timestamp":"2020-04-23T13:11:40.590876355Z","logLevel":"DEBUG","message":"Checking out ac2 branch"}
{"timestamp":"2020-04-23T13:11:40.69136954Z","logLevel":"DEBUG","message":"Archive the Helm chart: helm/inburgering.tgz"}
2020/04/23 13:11:40 http: panic serving 10.244.2.37:47462: runtime error: invalid memory address or nil pointer dereference
goroutine 1576 [running]:
net/http.(*conn).serve.func1(0xc0000de960)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x16f7bc0, 0x29a51e0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/keptn/keptn/configuration-service/handlers.GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHandlerFunc(0xc000464400, 0xc0007321b8, 0xc000656130, 0x3, 0xc0009360a0, 0x14, 0xc000656146, 0xb, 0xc00065613a, 0x3, ...)
	/go/src/github.com/keptn/keptn/configuration-service/handlers/service_resource.go:54 +0xc36
github.com/keptn/keptn/configuration-service/restapi/operations/service_resource.GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHandlerFunc.Handle(0x19c3638, 0xc000464400, 0xc0007321b8, 0xc000656130, 0x3, 0xc0009360a0, 0x14, 0xc000656146, 0xb, 0xc00065613a, ...)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/operations/service_resource/get_project_project_name_stage_stage_name_service_service_name_resource_resource_uri.go:19 +0x42
github.com/keptn/keptn/configuration-service/restapi/operations/service_resource.(*GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURI).ServeHTTP(0xc0005e3ec0, 0x1bb9aa0, 0xc000798540, 0xc000464400)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/operations/service_resource/get_project_project_name_stage_stage_name_service_service_name_resource_resource_uri.go:54 +0x212
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1bb9aa0, 0xc000798540, 0xc000464400)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0006b4ac0, 0x1bb9aa0, 0xc000798540, 0xc000464400)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1bb9aa0, 0xc000798540, 0xc000464100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc000947dc0, 0x1bb9aa0, 0xc000798540, 0xc000464100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x1bb9aa0, 0xc000798540, 0xc000464100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x2a5
net/http.HandlerFunc.ServeHTTP(0xc00094a180, 0x1bb9aa0, 0xc000798540, 0xc000464100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x1bb9aa0, 0xc000798540, 0xc000464100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc00094a1c0, 0x1bb9aa0, 0xc000798540, 0xc000464100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/keptn/keptn/configuration-service/restapi.setupGlobalMiddleware.func1(0x1bb9aa0, 0xc000798540, 0xc000464100)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/configure_configuration_service.go:179 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc00094e220, 0x1bb9aa0, 0xc000798540, 0xc000464100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc000828680, 0x1bb9aa0, 0xc000798540, 0xc000464100)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0000de960, 0x1bbeaa0, 0xc0008f0000)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
{"timestamp":"2020-04-23T13:20:50.864076351Z","logLevel":"DEBUG","message":"Checking out acc branch"}
{"timestamp":"2020-04-23T13:20:50.928093304Z","logLevel":"DEBUG","message":"Checking out master branch"}
{"timestamp":"2020-04-23T13:20:50.947856304Z","logLevel":"DEBUG","message":"Checking out acc branch"}
{"timestamp":"2020-04-23T13:20:50.961061271Z","logLevel":"DEBUG","message":"Checking out acc branch"}
{"timestamp":"2020-04-23T13:20:51.342718712Z","logLevel":"DEBUG","message":"Checking out acc branch"}
{"timestamp":"2020-04-23T13:20:51.43591147Z","logLevel":"DEBUG","message":"Checking out master branch"}
{"timestamp":"2020-04-23T13:20:51.452501402Z","logLevel":"DEBUG","message":"Checking out acc branch"}
{"timestamp":"2020-04-23T13:20:51.459820828Z","logLevel":"DEBUG","message":"Archive the Helm chart: helm/inburgering-generated.tgz"}
2020/04/23 13:20:51 http: panic serving 10.244.0.27:48384: runtime error: invalid memory address or nil pointer dereference
goroutine 1629 [running]:
net/http.(*conn).serve.func1(0xc0000dee60)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x16f7bc0, 0x29a51e0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/keptn/keptn/configuration-service/handlers.GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHandlerFunc(0xc000465900, 0xc000441feb, 0xc000654860, 0x3, 0xc0005c0260, 0x1e, 0xc000654876, 0xb, 0xc00065486a, 0x3, ...)
	/go/src/github.com/keptn/keptn/configuration-service/handlers/service_resource.go:54 +0xc36
github.com/keptn/keptn/configuration-service/restapi/operations/service_resource.GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHandlerFunc.Handle(0x19c3638, 0xc000465900, 0xc000441feb, 0xc000654860, 0x3, 0xc0005c0260, 0x1e, 0xc000654876, 0xb, 0xc00065486a, ...)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/operations/service_resource/get_project_project_name_stage_stage_name_service_service_name_resource_resource_uri.go:19 +0x42
github.com/keptn/keptn/configuration-service/restapi/operations/service_resource.(*GetProjectProjectNameStageStageNameServiceServiceNameResourceResourceURI).ServeHTTP(0xc0005e3ec0, 0x1bb9aa0, 0xc000798700, 0xc000465900)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/operations/service_resource/get_project_project_name_stage_stage_name_service_service_name_resource_resource_uri.go:54 +0x212
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1bb9aa0, 0xc000798700, 0xc000465900)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0006b4ac0, 0x1bb9aa0, 0xc000798700, 0xc000465900)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1bb9aa0, 0xc000798700, 0xc000523700)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc000947dc0, 0x1bb9aa0, 0xc000798700, 0xc000523700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x1bb9aa0, 0xc000798700, 0xc000523700)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x2a5
net/http.HandlerFunc.ServeHTTP(0xc00094a180, 0x1bb9aa0, 0xc000798700, 0xc000523700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x1bb9aa0, 0xc000798700, 0xc000523700)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc00094a1c0, 0x1bb9aa0, 0xc000798700, 0xc000523700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/keptn/keptn/configuration-service/restapi.setupGlobalMiddleware.func1(0x1bb9aa0, 0xc000798700, 0xc000523700)
	/go/src/github.com/keptn/keptn/configuration-service/restapi/configure_configuration_service.go:179 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc00094e220, 0x1bb9aa0, 0xc000798700, 0xc000523700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc000828680, 0x1bb9aa0, 0xc000798700, 0xc000523700)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0000dee60, 0x1bbeaa0, 0xc000267540)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

~~~~

**Comment by agrimmer** [comment]
The reason for this failure is that you have a full keptn installation, e.g. the `gatekeeper-service` is installed. With this installation, the gatekeeper sends out a `configuration.change`-event which does not work.
Furthermore, the quality-gates installation only allows a single stage.

In order to fix your installation, please execute `kubectl delete -f https://raw.githubusercontent.com/keptn/keptn/0.6.1/installer/manifests/keptn/continuous-deployment.yaml`.

I am closing this issue because the setting is invalid. However, if you need any further help, please reach out on Slack.

**Comment by agrimmer** [comment]
I reopened this issue because the `helm-service` should report that there is no onboard service available but must not leave the Git repo in an inconsistent state.

**Comment by agrimmer** [comment]
Let's reopen this issue and double-check whether a full-installation with a shipyard containing more than one stage can be used for _only_ checking the quality gates.

Therefore, the gatekeeper service must not send out a `configuration-change` event,
- if no `deployment_strategy` is defined in the shipyard for the next stage and 
- if the `evaluation-done` event does not contain any image or tag data.

**Comment by heydenb** [comment]
Hey guys, I have a 0.6.2 version with this thing still annoying me.
Is there a way I could already test this change without changing switching to a nightly build for everything? Maybe by just updating one service?

**Comment by agrimmer** [comment]
Hi @heydenb,
unfortunately, there is no version available because the fix in the gatekeeper-service would already contain other breaking changes. 
But if you only use quality gates, you can again execute `kubectl delete -f https://raw.githubusercontent.com/keptn/keptn/0.6.2/installer/manifests/keptn/continuous-deployment.yaml`. However, this would again prevent a successful upgrade of Keptn.

**Comment by heydenb** [comment]
Already found another workaround. I added an extra stage which I don't use.
