### ISSUE TITLE
JNLP container of Jenkins slaves run into a 'Connection refused' problem

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#226]
After setting up a new demo cluster based on the install instructions, all Jenkins slave pods run into a problem due to a `Connection refused`. This results in the issue that no Jenkins pipeline can get executed.  

1. Setting up a cluster
2. Following the steps of the [Onboarding a Service](https://keptn.sh/docs/0.2.0/usecases/onboard-carts-service/) use case 

**Expected behavior**
Slave pods start up and execute their job. 

**Environment**
Jenkins image: keptn/jenkins:0.3-rc

**Container Logs**
 Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
 Apr 02, 2019 1:27:37 AM hudson.remoting.jnlp.Main createEngine
 INFO: Setting up agent: maven-docker-k8s-jmeter-9b849
 Apr 02, 2019 1:27:38 AM hudson.remoting.jnlp.Main$CuiListener <init>
 INFO: Jenkins agent is running in headless mode.
 Apr 02, 2019 1:27:38 AM hudson.remoting.Engine startEngine
 INFO: Using Remoting version: 3.28
 Apr 02, 2019 1:27:38 AM hudson.remoting.Engine startEngine
 WARNING: No Working Directory. Using the legacy JAR Cache location: /home/jenkins/.jenkins/cache/jars
 Apr 02, 2019 1:27:38 AM hudson.remoting.jnlp.Main$CuiListener status
 INFO: Locating server among [http://jenkins.keptn.svc.cluster.local:80/]
 Apr 02, 2019 1:27:38 AM hudson.remoting.jnlp.Main$CuiListener error
 SEVERE: Failed to connect to http://jenkins.keptn.svc.cluster.local:80/tcpSlaveAgentListener/: Connection refused (Connection refused)
 java.io.IOException: Failed to connect to http://jenkins.keptn.svc.cluster.local:80/tcpSlaveAgentListener/: Connection refused (Connection refused)
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:197)
	at hudson.remoting.Engine.innerRun(Engine.java:523)
	at hudson.remoting.Engine.run(Engine.java:474)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:194)
	... 2 more

**Comment by agrimmer** [comment]
Joahnnes an me found a workaround for this issue.

Execute the following steps:
1.) Open Jenkins
2.) Select `Manage Jenkins`
3.) In the configuration of the Kubernetes plugin:
   a.) Delete `Jenkins URL`
   b.) Set `Jenkins tunnel` to `jenkins.keptn.svc.cluster.local:50000`
--

**Comment by agrimmer** [comment]
In order to close this issue, @johannes-b and me will update the Jenkins image.

**Comment by agrimmer** [comment]
**Solution:** Jenkins image (0.4.0) uses Jenkins tunnel instead of Jenkins URL.

**Comment by rranjith406** [comment]
your suggested solution didn't work for me. I have the same error. and looking for soltion

**Comment by ils-cicd** [comment]
I'm Facing the same issue.
