### ISSUE TITLE
Jenkins misses Jenkins URL Environment Variable on keptn0.2 default install

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#269]
**Describe the bug**
When onboarding a service as explained in keptn0.2 doc my Jenkins for the carts pipeline execution runs into the issue of not creating the maven pod. here is the stack trace from the Jenkins log
java.lang.IllegalStateException: Jenkins URL for Kubernetes is null
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.getJenkinsUrlOrDie(KubernetesCloud.java:301)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateBuilder.defaultEnvVars(PodTemplateBuilder.java:262)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateBuilder.createContainer(PodTemplateBuilder.java:310)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateBuilder.build(PodTemplateBuilder.java:151)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplate.build(PodTemplate.java:660)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.getPodTemplate(KubernetesLauncher.java:213)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:99)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
Execute the onboarding of the carts service use case

**Environment**
GKE 1.11 and keptn0.2 release

**Additional context**
Problem can be fixed by setting the JEnkins Url Environment Variable in the Global Jenkins Settings.

**Comment by johannes-b** [comment]
Jenkins URL added to Jenkins image 0.4.1

- [ ] Install keptn 0.2.0 to verify the use of the new image
